/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJDialog.java
 *
 * Created on 26 sept. 2011, 14:45:56
 */
package cpc.laboChimie.ui;

import cpc.laboChimie.jpa.Eau;
import cpc.laboChimie.metier.IMetier;
import cpc.laboChimie.metierConfig.ParametreGestion;
import cpc.laboChimie.model.TableModelNbreParametre;
import java.util.Date;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.TableModel;
import org.jdesktop.application.Action;
import jxl.*;
/**
 *
 * @author MAXWELL
 */
public class JdialogStatistique extends javax.swing.JDialog {
    private TableModelNbreParametre tableModelEau;
    private IMetier metier;
    /*private*/ Vector<Eau> ls = new Vector<Eau>();
    private Date deb;
    private Date fin;
    private ExporterExcel export;
    /** Creates new form NewJDialog */
    public JdialogStatistique(java.awt.Frame parent, boolean modal,Vector<Eau> a ,int op,Date debut,Date finh) {
        super(parent, modal);
        deb=debut;
        fin=finh;
        this.setTitle("STATISTIQUE DU LABORATOIRE");
        tableModelEau = new TableModelNbreParametre(a);
        initComponents();
        
        ls = a;
        System.out.println("JdialogStatistique taille eau ls = "+ls.size());
         mastertableEau.getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
         if(op==-1)
           { int som=0;
             jTextFieldanalyseMensuel.setText(""+tableModelEau.getRowCount());
             for(int i =0;i<a.size();i++ )
             {
               som = som + a.elementAt(i).getNombreEchantillon();
             }
             jTextFieldEchantillonmensuel.setText(""+som);
           }
        if (op ==1)
         {
           int som=0;
             jTextFieldAnalyseannuel.setText(""+tableModelEau.getRowCount());
             for(int i =0;i<a.size();i++ )
             {
               som = som + a.elementAt(i).getNombreEchantillon();
             }
             jTextFieldEchantillonAnnuel.setText(""+som);
           
         }
        
        
        this.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                       // System.exit(0);
                        
                            System.out.println("INTERFACE STATISTIQUE FERMETURE................");
                            fermer();
                    
                      
                    }
                });
    }

        public IMetier getMetier() {
        return metier;
    }

    public ExporterExcel getExport()
    {
      return export;
    }
        
    public void setExport(ExporterExcel ax)
    {
      export =ax;
    }
        

    ////Initialisation de l'application
    ParametreGestion parametreGestion;
    
    public void fermer()
     {
       tableModelEau.removeAll();
       this.setVisible(false);
     }

    public JLabel getjLabAnalyseMens()
     {
       return jLabelAnalyseMensuelle;
     }     
  
      public JLabel getjLabAnalyseAnuel()
     {
       return jLabelanalyseAnnuel;
     }     
  
    public JLabel getjLabEchtillonMens()
     {
       return jLabelEchantillonMensuel;
     }     
    
    public JTextField getJtextfieldDebPeriode()
     {
        return jTextFieldDebutPeriode;
     }
    
    public JTextField getJtextFieldFinPeriode()
      {
      
        return jTextFieldFinPeriode;
      }
    
    public JLabel getjLabEchtillonAn()
     {
       return jLabelEchantillonannuel;
     }     
    
    public JTextField getJtextAnalysemens()
     {
     
        return jTextFieldanalyseMensuel;
     }
    
    public JTextField getJtextAnalyseannuel()
     {
     
        return jTextFieldAnalyseannuel;
     }
    
    public JTextField getJtextEchantillonmens()
     {
     
        return jTextFieldEchantillonmensuel;
     }
    
      
    public JTextField getJtextEchantillonannuel()
     {
     
        return jTextFieldEchantillonAnnuel;
     }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mastertableEau = new org.jdesktop.swingx.JXTable();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDebutPeriode = new javax.swing.JTextField();
        jTextFieldFinPeriode = new javax.swing.JTextField();
        jLabelAnalyseMensuelle = new javax.swing.JLabel();
        jLabelEchantillonMensuel = new javax.swing.JLabel();
        jTextFieldanalyseMensuel = new javax.swing.JTextField();
        jTextFieldEchantillonmensuel = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldAnalyseannuel = new javax.swing.JTextField();
        jTextFieldEchantillonAnnuel = new javax.swing.JTextField();
        jLabelanalyseAnnuel = new javax.swing.JLabel();
        jLabelEchantillonannuel = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(cpc.laboChimie.mainApp.class).getContext().getResourceMap(JdialogStatistique.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jPanel2.setName("jPanel2"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        mastertableEau.setModel(tableModelEau);
        mastertableEau.setName("mastertableEau"); // NOI18N
        mastertableEau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mastertableEauMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(mastertableEau);

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jTextFieldDebutPeriode.setText(resourceMap.getString("jTextFieldDebutPeriode.text")); // NOI18N
        jTextFieldDebutPeriode.setEnabled(false);
        jTextFieldDebutPeriode.setName("jTextFieldDebutPeriode"); // NOI18N
        jTextFieldDebutPeriode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDebutPeriodeActionPerformed(evt);
            }
        });

        jTextFieldFinPeriode.setText(resourceMap.getString("jTextFieldFinPeriode.text")); // NOI18N
        jTextFieldFinPeriode.setEnabled(false);
        jTextFieldFinPeriode.setName("jTextFieldFinPeriode"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldDebutPeriode, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldFinPeriode, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDebutPeriode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFinPeriode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(270, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabelAnalyseMensuelle.setText(resourceMap.getString("jLabelAnalyseMensuelle.text")); // NOI18N
        jLabelAnalyseMensuelle.setName("jLabelAnalyseMensuelle"); // NOI18N

        jLabelEchantillonMensuel.setText(resourceMap.getString("jLabelEchantillonMensuel.text")); // NOI18N
        jLabelEchantillonMensuel.setName("jLabelEchantillonMensuel"); // NOI18N

        jTextFieldanalyseMensuel.setEditable(false);
        jTextFieldanalyseMensuel.setText(resourceMap.getString("jTextFieldanalyseMensuel.text")); // NOI18N
        jTextFieldanalyseMensuel.setName("jTextFieldanalyseMensuel"); // NOI18N

        jTextFieldEchantillonmensuel.setEditable(false);
        jTextFieldEchantillonmensuel.setText(resourceMap.getString("jTextFieldEchantillonmensuel.text")); // NOI18N
        jTextFieldEchantillonmensuel.setName("jTextFieldEchantillonmensuel"); // NOI18N

        jPanel3.setName("jPanel3"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTextFieldAnalyseannuel.setEditable(false);
        jTextFieldAnalyseannuel.setName("jTextFieldAnalyseannuel"); // NOI18N

        jTextFieldEchantillonAnnuel.setEditable(false);
        jTextFieldEchantillonAnnuel.setName("jTextFieldEchantillonAnnuel"); // NOI18N

        jLabelanalyseAnnuel.setText(resourceMap.getString("jLabelanalyseAnnuel.text")); // NOI18N
        jLabelanalyseAnnuel.setName("jLabelanalyseAnnuel"); // NOI18N

        jLabelEchantillonannuel.setText(resourceMap.getString("jLabelEchantillonannuel.text")); // NOI18N
        jLabelEchantillonannuel.setName("jLabelEchantillonannuel"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(cpc.laboChimie.mainApp.class).getContext().getActionMap(JdialogStatistique.class, this);
        jToggleButton1.setAction(actionMap.get("exporterExcel")); // NOI18N
        jToggleButton1.setText(resourceMap.getString("jToggleButton1.text")); // NOI18N
        jToggleButton1.setToolTipText(resourceMap.getString("jToggleButton1.toolTipText")); // NOI18N
        jToggleButton1.setName("jToggleButton1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(474, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEchantillonMensuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAnalyseMensuelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldanalyseMensuel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEchantillonmensuel))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelEchantillonannuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldAnalyseannuel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelanalyseAnnuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldEchantillonAnnuel)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelEchantillonannuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAnalyseannuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelanalyseAnnuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEchantillonAnnuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAnalyseMensuelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldanalyseMensuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelEchantillonMensuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEchantillonmensuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38)
                .addComponent(jToggleButton1)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mastertableEauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mastertableEauMouseClicked
        // TODO add your handling code here:
        //dès qu'on clique sur le Master Table on recupere toutes les eaux du client et on les affiche
        
        
     
    }//GEN-LAST:event_mastertableEauMouseClicked

    
  @Action
  public void  exporterExcel()
   {  int nbfich;
     // JOptionPane.showMessageDialog(null, "EXPORTATION DES DONNEES");
      /*
      * Conslter le nombre de type d'eau
       * Créer un fichier excel pour chaque type d'eau retrouver
       * remplir les attributs colones par es noms des paramètres
       * insérer les données
       * 
       */
       System.out.println("LS  ="+ ls.size());
       export = new ExporterExcel(null,this,ls, deb, fin);
      export.setVisible(true);
      fermer(); 
      //quitter 
      
      
   }
    
    
    
    private void jTextFieldDebutPeriodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDebutPeriodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDebutPeriodeActionPerformed

    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                JdialogStatistique dialog = new JdialogStatistique(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAnalyseMensuelle;
    private javax.swing.JLabel jLabelEchantillonMensuel;
    private javax.swing.JLabel jLabelEchantillonannuel;
    private javax.swing.JLabel jLabelanalyseAnnuel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldAnalyseannuel;
    private javax.swing.JTextField jTextFieldDebutPeriode;
    private javax.swing.JTextField jTextFieldEchantillonAnnuel;
    private javax.swing.JTextField jTextFieldEchantillonmensuel;
    private javax.swing.JTextField jTextFieldFinPeriode;
    private javax.swing.JTextField jTextFieldanalyseMensuel;
    private javax.swing.JToggleButton jToggleButton1;
    private org.jdesktop.swingx.JXTable mastertableEau;
    // End of variables declaration//GEN-END:variables
}
