/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDialogAnalyseMensuel.java
 *
 * Created on 26 sept. 2011, 13:54:35
 */
package cpc.laboChimie.ui;

import java.util.Date;
import java.util.List;
import cpc.laboChimie.jpa.Eau;
import javax.swing.JOptionPane;
import org.jdesktop.application.Action;
import cpc.laboChimie.metier.IMetier;
import cpc.laboChimie.metierConfig.ParametreGestion;
import java.text.DateFormat;
import java.util.Locale;
import java.util.Vector;

/**
 *
 * @author MAXWELL
 */
public class JDialogAnalyseMensuel extends javax.swing.JDialog {
    
    private List<Eau> ls;
    private IMetier metier;
    private Vector<Eau> eaux;
    private JDialogAdmin ad;
    private JFChefLabo jChef;
    Date d1;
    Date d2;
    
    /** Creates new form JDialogAnalyseMensuel */
    public JDialogAnalyseMensuel(java.awt.Frame parent, boolean modal, JFChefLabo chef, JDialogAdmin admin) {
        super(parent, modal);
        initSpring();
        initComponents();
        ad = admin;
        jChef = chef;
        this.setTitle("SELECTION DE LA PERIODE");
        eaux = new Vector<Eau>();        
    }

        private void initSpring() {
        parametreGestion = ParametreGestion.getInstance();
       metier = parametreGestion.getMetier();
  }
    
        public IMetier getMetier() {
        return metier;
    }

    public Vector<Eau> getEauperiode()
      {
        return eaux;
      }

    ////Initialisation de l'application
    ParametreGestion parametreGestion;

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
   public List<Eau> getAllEauPeriode()
      {
        return ls;
      }
    
    public void setAllEauPeriode(List<Eau> ls)
     {
       this.ls = ls;
     }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jXDatePicker_Debut = new org.jdesktop.swingx.JXDatePicker();
        jXDatePicker_Fin = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(cpc.laboChimie.mainApp.class).getContext().getResourceMap(JDialogAnalyseMensuel.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(cpc.laboChimie.mainApp.class).getContext().getActionMap(JDialogAnalyseMensuel.class, this);
        jToggleButton1.setAction(actionMap.get("ListerEauNbreParam")); // NOI18N
        jToggleButton1.setText(resourceMap.getString("jToggleButton1.text")); // NOI18N
        jToggleButton1.setName("jToggleButton1"); // NOI18N

        jXDatePicker_Debut.setFocusable(false);
        jXDatePicker_Debut.setName("jXDatePicker_Debut"); // NOI18N

        jXDatePicker_Fin.setFocusable(false);
        jXDatePicker_Fin.setName("jXDatePicker_Fin"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jXDatePicker_Debut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jLabel3)
                        .addGap(33, 33, 33)
                        .addComponent(jXDatePicker_Fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jToggleButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jXDatePicker_Debut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXDatePicker_Fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addComponent(jToggleButton1)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                JDialogAnalyseMensuel dialog = new JDialogAnalyseMensuel(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/

    @Action
    public void ListerEauNbreParam() {
   
        //recupere les parametres ie date de debut et date de fin 
         d1  = this.jXDatePicker_Debut.getDate();
         d2 =  this.jXDatePicker_Fin.getDate();
        
        if (d2==null)
         {
           JOptionPane.showMessageDialog(null, " VEUILLEZ ENTREZ UN DATE DE FIN");
           return;
         }
    
      if(d2.compareTo(d1)<0)
       {
             JOptionPane.showMessageDialog(null, " VEUILLEZ ENTREZ LES DATES DANS L\'ORDRE ");
           return;
       
       }
         //appel de la fonction metier
        ls = metier.getAllEau();
        if(ls!=null)
        {for(Eau e : ls)
          {if(e.getDateLivraison()!=null)
             if(e.getDateLivraison().compareTo(d1)>0 && d2.compareTo(e.getDateLivraison())>0)
                eaux.add(e);
          }
        }else
           JOptionPane.showMessageDialog(null, "AUCUNE EAU N'A ETE ANALYSE DURANT  CETTE PERIODE ");
               
        
        if(eaux==null)
        {
           JOptionPane.showMessageDialog(null, "AUCUNE EAU N'A ETE ANALYSE DURANT  CETTE PERIODE ");
           return;
       
        }
      
        //suivant l'opération active l'interface
        if(ad!=null)
         { if(ad.getopStat()==-1)//gestion mensuelle
            {  JdialogStatistique stat = new JdialogStatistique(null, true, eaux,-1,d1,d2);
               stat.getjLabAnalyseAnuel().setVisible(false);
               stat.getJtextAnalyseannuel().setVisible(false);
               stat.getjLabEchtillonAn().setVisible(false);
               stat.getJtextEchantillonannuel().setVisible(false);
               
               stat.getJtextfieldDebPeriode().setText(DateFormat.getDateInstance(DateFormat.MEDIUM, Locale.FRANCE).format(d1));
               stat.getJtextFieldFinPeriode().setText(DateFormat.getDateInstance(DateFormat.MEDIUM, Locale.FRANCE).format(d2));

               stat.setVisible(true);
             
            }
           if(ad.getopStat()==1)
            {
              JdialogStatistique stat = new JdialogStatistique(null, true, eaux,1,d1,d2);
               stat.getjLabAnalyseMens().setVisible(false);
               stat.getJtextAnalysemens().setVisible(false);
               stat.getjLabEchtillonMens().setVisible(false);
               stat.getJtextEchantillonmens().setVisible(false);
               
               stat.getJtextfieldDebPeriode().setText(DateFormat.getDateInstance(DateFormat.MEDIUM, Locale.FRANCE).format(d1));
               stat.getJtextFieldFinPeriode().setText(DateFormat.getDateInstance(DateFormat.MEDIUM, Locale.FRANCE).format(d2));

               stat.setVisible(true);
            
            }
         }
        else // CHEF DE LABORATOIRE
        {  if(jChef.getOpStat()==-1)//gestion mensuelle
            {  JdialogStatistique stat = new JdialogStatistique(null, true, eaux,-1,d1,d2);
               stat.getjLabAnalyseAnuel().setVisible(false);
               stat.getJtextAnalyseannuel().setVisible(false);
               stat.getjLabEchtillonAn().setVisible(false);
               stat.getJtextEchantillonannuel().setVisible(false);

               stat.getJtextfieldDebPeriode().setText(DateFormat.getDateInstance(DateFormat.MEDIUM, Locale.FRANCE).format(d1));
               stat.getJtextFieldFinPeriode().setText(DateFormat.getDateInstance(DateFormat.MEDIUM, Locale.FRANCE).format(d2));

               
               stat.setVisible(true);
             
            }
           if(jChef.getOpStat()==1)
            {
              JdialogStatistique stat = new JdialogStatistique(null, true, eaux,1,d1,d2);
               stat.getjLabAnalyseMens().setVisible(false);
               stat.getJtextAnalysemens().setVisible(false);
               stat.getjLabEchtillonMens().setVisible(false);
               stat.getJtextEchantillonmens().setVisible(false);
               
               
               stat.getJtextfieldDebPeriode().setText(DateFormat.getDateInstance(DateFormat.MEDIUM, Locale.FRANCE).format(d1));
               stat.getJtextFieldFinPeriode().setText(DateFormat.getDateInstance(DateFormat.MEDIUM, Locale.FRANCE).format(d2));

               stat.setVisible(true);
            
            }
         
        
        }
        
        //fermer
        this.setVisible(false);
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToggleButton jToggleButton1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker_Debut;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker_Fin;
    // End of variables declaration//GEN-END:variables
}
