/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDialogClient.java
 *
 * Created on 13 juin 2011, 14:26:45
 */

package cpc.laboChimie.ui;

import cpc.laboChimie.jpa.Client;
import cpc.laboChimie.metier.IMetier;
import cpc.laboChimie.metierConfig.ParametreGestion;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JToggleButton;
import org.jdesktop.application.Action;

/**
 *
 * @author HP
 */
public class JDialogClient extends javax.swing.JDialog {

    private JFChefLabo jchef;
    
    /** Creates new form JDialogClient */
  static  private JDialogAdmin Jadmin = null;
   IMetier metier;
    public JDialogClient(java.awt.Frame parent, boolean modal,JDialogTechnicien  tech,JFChefLabo chef ,JDialogAdmin admin) {
        super(parent, modal);
        Jadmin=admin;
        jchef =chef;
        metier = ParametreGestion.getInstance().getMetier();
        initComponents();
        reinit();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldNomDemandeur = new javax.swing.JTextField();
        jTextField_Bp_Demandeur = new javax.swing.JTextField();
        jTextField_ville_Demandeur = new javax.swing.JTextField();
        jTextField_Tel_Demandeur = new javax.swing.JTextField();
        jTextField_couriel_Demandeur = new javax.swing.JTextField();
        jTextField_Fax_Demandeur = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldNom_Payeur = new javax.swing.JTextField();
        jTextFieldTel_Payeur = new javax.swing.JTextField();
        jTextField_couriel_Payeur = new javax.swing.JTextField();
        jTextField_Fax_Payeur = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField_nom_Personne = new javax.swing.JTextField();
        jTextField_tel_Personne = new javax.swing.JTextField();
        jTextField_couriel_Personne = new javax.swing.JTextField();
        jTextField_Fax_Personne = new javax.swing.JTextField();
        jLabeliDClient = new javax.swing.JLabel();
        jTextField_id_client = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jToggleButtonEnregistrer = new javax.swing.JToggleButton();
        jToggleButtonModifier = new javax.swing.JToggleButton();
        jToggleButtonfermer = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        jPanel2.setName("jPanel2"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(cpc.laboChimie.mainApp.class).getContext().getResourceMap(JDialogClient.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jTextFieldNomDemandeur.setText(resourceMap.getString("jTextFieldNomDemandeur.text")); // NOI18N
        jTextFieldNomDemandeur.setName("jTextFieldNomDemandeur"); // NOI18N

        jTextField_Bp_Demandeur.setText(resourceMap.getString("jTextField_Bp_Demandeur.text")); // NOI18N
        jTextField_Bp_Demandeur.setName("jTextField_Bp_Demandeur"); // NOI18N
        jTextField_Bp_Demandeur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Bp_DemandeurActionPerformed(evt);
            }
        });

        jTextField_ville_Demandeur.setText(resourceMap.getString("jTextField_ville_Demandeur.text")); // NOI18N
        jTextField_ville_Demandeur.setName("jTextField_ville_Demandeur"); // NOI18N

        jTextField_Tel_Demandeur.setText(resourceMap.getString("jTextField_Tel_Demandeur.text")); // NOI18N
        jTextField_Tel_Demandeur.setName("jTextField_Tel_Demandeur"); // NOI18N

        jTextField_couriel_Demandeur.setText(resourceMap.getString("jTextField_couriel_Demandeur.text")); // NOI18N
        jTextField_couriel_Demandeur.setName("jTextField_couriel_Demandeur"); // NOI18N

        jTextField_Fax_Demandeur.setText(resourceMap.getString("jTextField_Fax_Demandeur.text")); // NOI18N
        jTextField_Fax_Demandeur.setName("jTextField_Fax_Demandeur"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_ville_Demandeur, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                                            .addComponent(jTextField_Tel_Demandeur, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                                            .addComponent(jTextField_couriel_Demandeur, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                                            .addComponent(jTextField_Fax_Demandeur, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField_Bp_Demandeur)
                                            .addComponent(jTextFieldNomDemandeur, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNomDemandeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_Bp_Demandeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField_couriel_Demandeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField_Fax_Demandeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField_ville_Demandeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Tel_Demandeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setName("jPanel3"); // NOI18N

        jLabel14.setText(resourceMap.getString("jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N

        jLabel15.setText(resourceMap.getString("jLabel15.text")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N

        jLabel16.setText(resourceMap.getString("jLabel16.text")); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N

        jLabel17.setText(resourceMap.getString("jLabel17.text")); // NOI18N
        jLabel17.setName("jLabel17"); // NOI18N

        jLabel18.setText(resourceMap.getString("jLabel18.text")); // NOI18N
        jLabel18.setName("jLabel18"); // NOI18N

        jTextFieldNom_Payeur.setText(resourceMap.getString("jTextFieldNom_Payeur.text")); // NOI18N
        jTextFieldNom_Payeur.setName("jTextFieldNom_Payeur"); // NOI18N

        jTextFieldTel_Payeur.setText(resourceMap.getString("jTextFieldTel_Payeur.text")); // NOI18N
        jTextFieldTel_Payeur.setName("jTextFieldTel_Payeur"); // NOI18N

        jTextField_couriel_Payeur.setText(resourceMap.getString("jTextField_couriel_Payeur.text")); // NOI18N
        jTextField_couriel_Payeur.setName("jTextField_couriel_Payeur"); // NOI18N

        jTextField_Fax_Payeur.setText(resourceMap.getString("jTextField_Fax_Payeur.text")); // NOI18N
        jTextField_Fax_Payeur.setName("jTextField_Fax_Payeur"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField_couriel_Payeur))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15)
                                .addComponent(jLabel16))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldTel_Payeur)
                                .addComponent(jTextFieldNom_Payeur, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel18)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField_Fax_Payeur))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldNom_Payeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldTel_Payeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField_couriel_Payeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField_Fax_Payeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jPanel4.setName("jPanel4"); // NOI18N

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N

        jTextField_nom_Personne.setText(resourceMap.getString("jTextField_nom_Personne.text")); // NOI18N
        jTextField_nom_Personne.setName("jTextField_nom_Personne"); // NOI18N

        jTextField_tel_Personne.setText(resourceMap.getString("jTextField_tel_Personne.text")); // NOI18N
        jTextField_tel_Personne.setName("jTextField_tel_Personne"); // NOI18N

        jTextField_couriel_Personne.setText(resourceMap.getString("jTextField_couriel_Personne.text")); // NOI18N
        jTextField_couriel_Personne.setName("jTextField_couriel_Personne"); // NOI18N

        jTextField_Fax_Personne.setText(resourceMap.getString("jTextField_Fax_Personne.text")); // NOI18N
        jTextField_Fax_Personne.setName("jTextField_Fax_Personne"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_nom_Personne, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                            .addComponent(jTextField_tel_Personne)
                            .addComponent(jTextField_Fax_Personne)
                            .addComponent(jTextField_couriel_Personne)))
                    .addComponent(jLabel9))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField_nom_Personne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jTextField_tel_Personne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField_couriel_Personne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jTextField_Fax_Personne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabeliDClient.setText(resourceMap.getString("jLabeliDClient.text")); // NOI18N
        jLabeliDClient.setName("jLabeliDClient"); // NOI18N

        jTextField_id_client.setEditable(false);
        jTextField_id_client.setText(resourceMap.getString("jTextField_id_client.text")); // NOI18N
        jTextField_id_client.setName("jTextField_id_client"); // NOI18N

        jPanel5.setName("jPanel5"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(cpc.laboChimie.mainApp.class).getContext().getActionMap(JDialogClient.class, this);
        jToggleButtonEnregistrer.setAction(actionMap.get("enregistrerClient")); // NOI18N
        jToggleButtonEnregistrer.setText(resourceMap.getString("jToggleButtonEnregistrer.text")); // NOI18N
        jToggleButtonEnregistrer.setName("jToggleButtonEnregistrer"); // NOI18N

        jToggleButtonModifier.setAction(actionMap.get("modifierClient")); // NOI18N
        jToggleButtonModifier.setText(resourceMap.getString("jToggleButtonModifier.text")); // NOI18N
        jToggleButtonModifier.setName("jToggleButtonModifier"); // NOI18N

        jToggleButtonfermer.setAction(actionMap.get("fermerFrameClient")); // NOI18N
        jToggleButtonfermer.setText(resourceMap.getString("jToggleButtonfermer.text")); // NOI18N
        jToggleButtonfermer.setName("jToggleButtonfermer"); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToggleButtonEnregistrer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButtonModifier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButtonfermer)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonEnregistrer)
                    .addComponent(jToggleButtonModifier)
                    .addComponent(jToggleButtonfermer))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabeliDClient)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_id_client, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeliDClient)
                    .addComponent(jTextField_id_client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_Bp_DemandeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Bp_DemandeurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Bp_DemandeurActionPerformed


    
     public JLabel getJLabelIdClient()
      {
         return jLabeliDClient;
      }
      
     public JTextField getJtextfieldIdClient()
     {
        return jTextField_id_client;
       
     }
    
    public Client getClientInterface()
    {  Client c = new Client();
       /**
        * Le Demandeur
        */
        c.setNomDemandeur(this.jTextFieldNomDemandeur.getText());
        c.setEmailDemandeur(this.jTextField_couriel_Demandeur.getText());
        c.setBp(this.jTextField_Bp_Demandeur.getText());
        c.setVille(this.jTextField_ville_Demandeur.getText());
        c.setTelDemandeur(this.jTextField_Tel_Demandeur.getText());
        c.setFaxDemandeur(this.jTextField_Fax_Demandeur.getText());
        /**
         * Le payeur
         */
        c.setNomPayeur(this.jTextFieldNom_Payeur.getText());
        c.setEmailPayeur(this.jTextField_couriel_Payeur.getText());
        c.setFaxPayeur(this.jTextField_Fax_Payeur.getText());
        c.setTelPayeur(this.jTextFieldTel_Payeur.getText());

        /**
         * La personne à contacter si besoin
         */
        c.setNomPersContact(this.jTextField_nom_Personne.getText());
        c.setEmailPersContact(this.jTextField_couriel_Payeur.getText());
        c.setFaxPersContact(this.jTextField_Fax_Personne.getText());
        c.setTelPersContact(this.jTextField_tel_Personne.getText());
        return c;
    }

public void setClientInterface(Client c)
{
  this.jTextField_id_client.setText(c.getId().toString());
  this.jTextFieldNomDemandeur.setText(c.getNomDemandeur());
  this.jTextField_couriel_Demandeur.setText(c.getEmailDemandeur());
  this.jTextField_Bp_Demandeur.setText(c.getBp());
  this.jTextField_ville_Demandeur.setText(c.getVille());
  this.jTextField_Tel_Demandeur.setText(c.getTelDemandeur());
  this.jTextField_Fax_Demandeur.setText(c.getFaxDemandeur());
  this.jTextFieldNom_Payeur.setText(c.getNomPayeur());
        this.jTextField_couriel_Payeur.setText(c.getEmailPayeur());
        this.jTextField_Fax_Payeur.setText(c.getFaxPayeur());
        this.jTextFieldTel_Payeur.setText(c.getTelPayeur());


       this.jTextField_nom_Personne.setText(c.getNomPersContact());
       this.jTextField_couriel_Payeur.setText(c.getEmailPersContact());
       this.jTextField_Fax_Personne.setText(c.getFaxPersContact());
       this.jTextField_tel_Personne.setText(c.getTelPersContact());

}

//initialise les champs de la fenêtre
public void reinit()
{
  this.jTextFieldNomDemandeur.setText("");
  this.jTextField_couriel_Demandeur.setText("");
  this.jTextField_Bp_Demandeur.setText("");
  this.jTextField_ville_Demandeur.setText("");
  this.jTextField_Tel_Demandeur.setText("");
  this.jTextField_Fax_Demandeur.setText("");
  this.jTextFieldNom_Payeur.setText("");
        this.jTextField_couriel_Payeur.setText("");
        this.jTextField_Fax_Payeur.setText("");
        this.jTextFieldTel_Payeur.setText("");


       this.jTextField_nom_Personne.setText("");
       this.jTextField_couriel_Payeur.setText("");
       this.jTextField_Fax_Personne.setText("");
       this.jTextField_tel_Personne.setText("");

}
    /**
    * @param args the command line arguments
    */
  /*  public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogClient dialog = new JDialogClient(new javax.swing.JFrame(), true,Jadmin,null,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/

    @Action
    public void enregistrerClient() {
       Client c = getClientInterface();
       if(c.getNomDemandeur()==null)
       { //Veuillez remplir les champs de l'interface
           JOptionPane.showMessageDialog(null, "Veuillez remplir au moins le nom du Demandeur");
       }
       else
       {  //appel code metier
           //Vérifier si le client n'est pas déja dans la BD
          /* if(metier.getClientByNom(jTextFieldNomDemandeur.getText())!=null)
           {
               JOptionPane.showMessageDialog(null,"VEUILLLEZ SAISIR UN NOM DE DEMANDEUR DIFFERENT S\'IL VOUS PLAIT");
             return;
             
           }*/
             metier.saveClient(c);
             if(Jadmin!=null)
              Jadmin.getTableModelClient().addRow(c);
             if(jchef!=null)
                  jchef.getTableModelClient().addRow(c);
            reinit();
       }
          this.fermerFrameClient();
    }

    @Action
    public void modifierClient() {
              Client c = getClientInterface();

        if (c != null) {
            c.setId(Long.parseLong(jTextField_id_client.getText()));
            metier.updateClient(c);
            if(Jadmin!=null)
            {Jadmin.getTableModelClient().removeRow(c);
            Jadmin.getTableModelClient().addRow(c);
            }
            if(jchef!=null)
            {
            jchef.getTableModelClient().removeRow(c);
            jchef.getTableModelClient().addRow(c);
            
            }
        } else {
            JOptionPane.showMessageDialog(this, "Problème dans les champs");
        }

        this.fermerFrameClient();

    }

    @Action
    public void fermerFrameClient() {
        reinit();
        this.setVisible(false);
        if(Jadmin!=null)
           Jadmin.setjDialogClient(null);
        if(jchef!=null)
           jchef.setjDialogClient(null);
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabeliDClient;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextFieldNomDemandeur;
    private javax.swing.JTextField jTextFieldNom_Payeur;
    private javax.swing.JTextField jTextFieldTel_Payeur;
    private javax.swing.JTextField jTextField_Bp_Demandeur;
    private javax.swing.JTextField jTextField_Fax_Demandeur;
    private javax.swing.JTextField jTextField_Fax_Payeur;
    private javax.swing.JTextField jTextField_Fax_Personne;
    private javax.swing.JTextField jTextField_Tel_Demandeur;
    private javax.swing.JTextField jTextField_couriel_Demandeur;
    private javax.swing.JTextField jTextField_couriel_Payeur;
    private javax.swing.JTextField jTextField_couriel_Personne;
    private javax.swing.JTextField jTextField_id_client;
    private javax.swing.JTextField jTextField_nom_Personne;
    private javax.swing.JTextField jTextField_tel_Personne;
    private javax.swing.JTextField jTextField_ville_Demandeur;
    private javax.swing.JToggleButton jToggleButtonEnregistrer;
    private javax.swing.JToggleButton jToggleButtonModifier;
    private javax.swing.JToggleButton jToggleButtonfermer;
    // End of variables declaration//GEN-END:variables

    public JToggleButton getjToggleButtonEnregistrer() {
        return jToggleButtonEnregistrer;
    }

    public void setjToggleButtonEnregistrer(JToggleButton jToggleButtonEnregistrer) {
        this.jToggleButtonEnregistrer = jToggleButtonEnregistrer;
    }

    public JToggleButton getjToggleButtonFermer() {
        return jToggleButtonfermer;
    }

    public void setjToggleButtonFermer(JToggleButton jToggleButtonFermer) {
        this.jToggleButtonfermer = jToggleButtonFermer;
    }

    public JToggleButton getjToggleButtonModifier() {
        return jToggleButtonModifier;
    }

    public void setjToggleButtonModifier(JToggleButton jToggleButtonModifier) {
        this.jToggleButtonModifier = jToggleButtonModifier;
    }
}
