/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDialogGroupClass.java
 *
 * Created on 19 oct. 2011, 09:48:48
 */
package cpc.laboChimie.ui;

import cpc.laboChimie.jpa.GroupClassEau;
import cpc.laboChimie.metier.IMetier;
import cpc.laboChimie.metierConfig.ParametreGestion;
import javax.swing.JOptionPane;
import org.jdesktop.application.Action;

/**
 *
 * @author HP
 */
public class JDialogGroupClass extends javax.swing.JDialog {
    private IMetier metier;
    private JDialogAdmin jadmin;
    private JFChefLabo   jchef;
    /** Creates new form JDialogGroupClass */
    public JDialogGroupClass(java.awt.Frame parent, boolean modal, JDialogAdmin jad,JFChefLabo jch) {
        super(parent, modal);
        initComponents();
        initSpring();
        jadmin =jad;
        jchef = jch;
        jTextFieldSpecification.setText("");
        this.setTitle("CREATION D\'UNE CLASSE OU GROUPE ");
    }

    
    
     public IMetier getMetier() {
        return metier;
    }
  
    ////Initialisation du masque de saisie
    ParametreGestion parametreGestion;

    private void initSpring() {
       parametreGestion = ParametreGestion.getInstance();
       metier = parametreGestion.getMetier();
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxGroupClass = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldSpecification = new javax.swing.JTextField();
        jToggleButtonajouter = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(cpc.laboChimie.mainApp.class).getContext().getResourceMap(JDialogGroupClass.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jComboBoxGroupClass.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "groupe", "classe" }));
        jComboBoxGroupClass.setName("jComboBoxGroupClass"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jTextFieldSpecification.setText(resourceMap.getString("jTextFieldSpecification.text")); // NOI18N
        jTextFieldSpecification.setName("jTextFieldSpecification"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(cpc.laboChimie.mainApp.class).getContext().getActionMap(JDialogGroupClass.class, this);
        jToggleButtonajouter.setAction(actionMap.get("AjouterGroupeClasse")); // NOI18N
        jToggleButtonajouter.setText(resourceMap.getString("jToggleButtonajouter.text")); // NOI18N
        jToggleButtonajouter.setName("jToggleButtonajouter"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldSpecification, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jComboBoxGroupClass, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jToggleButtonajouter)
                        .addGap(266, 266, 266))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxGroupClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSpecification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jToggleButtonajouter)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                JDialogGroupClass dialog = new JDialogGroupClass(new javax.swing.JFrame(), true,null,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    @Action
    public void AjouterGroupeClasse() {
      if(!jTextFieldSpecification.getText().equals("") && jComboBoxGroupClass.getSelectedItem()!=null )
      {
         GroupClassEau grpclas = new GroupClassEau();
         
         grpclas.setTypeGroupClass(jComboBoxGroupClass.getSelectedItem().toString());
         grpclas.setnouvelleclasseGroupEau(jTextFieldSpecification.getText());
         
         metier.saveGroupClass(grpclas);
         //Enregistre
         
         JOptionPane.showMessageDialog(null, "La CLASSE/GROUPE:\n  "+jTextFieldSpecification.getText());
          
      }
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxGroupClass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextFieldSpecification;
    private javax.swing.JToggleButton jToggleButtonajouter;
    // End of variables declaration//GEN-END:variables
}
