/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDialogcreerEau.java
 *
 * Created on 22 août 2011, 00:48:27
 */

package cpc.laboChimie.ui;

import cpc.laboChimie.jpa.TypeEau;
import cpc.laboChimie.metier.IMetier;
import cpc.laboChimie.metierConfig.ParametreGestion;
import javax.swing.JOptionPane;

/**
 *
 * @author MAXWELL
 */
public class JDialogcreerTypeEau extends javax.swing.JDialog {

    JDialogAdmin jadmin;
    private IMetier metier;
//    private JFrameParametres JFnorm;
    private JFrameParametrefinal JFparam;
    private JFChefLabo jCheflab;
    private  TypeEau t;
    //    private JFrameParametres JFnorm;
    private long idTyEau;
    /** Creates new form JDialogcreerEau */
    public JDialogcreerTypeEau(java.awt.Frame parent, boolean modal,JFChefLabo jchf,JDialogAdmin j) {
        super(parent, modal);
        this.setTitle("CREATION D\'UN TYPE D\'EAU");
        initComponents();
        initSpring();
        this.jadmin = j;
        jCheflab = jchf;
    }

      public IMetier getMetier() {
        return metier;
    }

       public long getidTypeEau() {
        return idTyEau;
    }
      public void setidTypEau(long id) {
        idTyEau = id;
    }

      
    ////Initialisation du masque de saisie
    ParametreGestion parametreGestion;

    private void initSpring() {
       parametreGestion = ParametreGestion.getInstance();
       metier = parametreGestion.getMetier();

    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(cpc.laboChimie.mainApp.class).getContext().getResourceMap(JDialogcreerTypeEau.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
        jTextField1.setName("jTextField1"); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:

        if(jTextField1.getText().equals(""))
        {
          JOptionPane.showMessageDialog(null, "VEUILLEZ ENTRER UN TYPE D\'EAU");
          return;
          
            }
        if(metier.getTypeEau(jTextField1.getText())!=null)
        {
           JOptionPane.showMessageDialog(null, "CE TYPE D\'EAU EXISTE DEJA CREER UN AUTRE");
           return;
        }
        
         t = new TypeEau();
        t.setCategorie(jTextField1.getText());
        metier.saveTypeEau(t);
        
        //recupere l'id et passe le au fils
        setidTypEau(metier.getTypeEau(jTextField1.getText()).getId().longValue());
         System.out.println("id = "+idTyEau);
        //JFnorm = new JFrameParametres(null,true,null,this,null);
       // JFnorm = new JFrameParametres(null,true,null,this,null);
        JFparam = new JFrameParametrefinal(null, true,this,null,null,null,null);
        //JFnorm.setVisible(true);
         JFparam.setCodeOperation(1);// Pour ajouter des normes au type d'eau sélectionné
        JFparam.getJLabelListerNorme().setVisible(false);
        JFparam.getjToggleButtonListerNormes().setVisible(false);
        JFparam.setVisible(true);
        fermer();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
    * @param args the command line arguments
    */
   /* public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogcreerEau dialog = new JDialogcreerEau(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void fermer() {
     //   throw new UnsupportedOperationException("Not yet implemented");
        
       System.out.println("FERMETURE DE LA FENETRE CREATION TYPE EAU");    
       this.setVisible(false);
       if(this.jadmin!=null)
        this.jadmin.setJDialogCreerTypeEau(null);
       if(this.jCheflab!=null)
           this.jCheflab.setJDialogCreerTypeEau(null);
       
        
    }

    String getNomTypEau() {
        //throw new UnsupportedOperationException("Not yet implemented");
        
        return t.getCategorie();
    }

}
