/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDialogTypEau.java
 *
 * Created on 6 sept. 2011, 23:20:12
 */
package cpc.laboChimie.ui;

import cpc.laboChimie.jpa.Eau;
import cpc.laboChimie.jpa.EauCategorie;
import cpc.laboChimie.jpa.TypeEau;
import cpc.laboChimie.metier.IMetier;
import cpc.laboChimie.metierConfig.ParametreGestion;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import org.jdesktop.application.Action;

/**
 *
 * @author HP
 */
public class JDialogTypEau extends javax.swing.JDialog {
private List<TypeEau> list_typeEau;
    private IMetier metier;
    static JDialogAdmin jadmin;
    private JFChefLabo jchef;
    /** Creates new form JDialogTypEau */
    public JDialogTypEau(java.awt.Frame parent, boolean modal,JFChefLabo jf ,JDialogAdmin j) {
        super(parent, modal);
        this.jadmin = j;
        this.jchef =jf;
        initComponents();
        initSpring();
        jTextField1.setText("");
        jTextField2.setText("");
        
    }

    
    
    ////Initialisation du masque de saisie
    ParametreGestion parametreGestion;

    private void initSpring() {
       parametreGestion = ParametreGestion.getInstance();
       metier = parametreGestion.getMetier();
       list_typeEau =  metier.getAllTypeEau();
      if(list_typeEau==null)
          return;
      else
         System.out.println("Remlissage de la JComboBox");

   for( TypeEau t  : list_typeEau)
      { 
          if (t!=null)
      jComboBox1.addItem(t.getCategorie());
              //System.out.println(" categorie elem "+t.getCategorie());
          else
              System.out.println("Erreur pas de TypeEau");
      }
   }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(cpc.laboChimie.mainApp.class).getContext().getResourceMap(JDialogTypEau.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jComboBox1.setName("jComboBox1"); // NOI18N
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(cpc.laboChimie.mainApp.class).getContext().getActionMap(JDialogTypEau.class, this);
        jToggleButton1.setAction(actionMap.get("ModifierTypeEau")); // NOI18N
        jToggleButton1.setText(resourceMap.getString("jToggleButton1.text")); // NOI18N
        jToggleButton1.setName("jToggleButton1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setEnabled(false);
        jLabel2.setName("jLabel2"); // NOI18N

        jTextField1.setEditable(false);
        jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
        jTextField1.setEnabled(false);
        jTextField1.setName("jTextField1"); // NOI18N

        jTextField2.setText(resourceMap.getString("jTextField2.text")); // NOI18N
        jTextField2.setEnabled(false);
        jTextField2.setName("jTextField2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setEnabled(false);
        jLabel3.setName("jLabel3"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(224, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addGap(105, 105, 105))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1)
                        .addGap(46, 46, 46)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))))
                .addContainerGap(53, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
        
        // Dès qu'il sélectionne l'eau on active les composants de l'interface
  
        Object o = evt.getSource();

        if(o instanceof JComboBox)
        { JComboBox jb = (JComboBox) evt.getSource();
          System.out.println("un element a ete selectionné");
         // JOptionPane.showMessageDialog(null,jb.getSelectedItem().toString());
        this.jTextField1.setText(jb.getSelectedItem().toString());
        this.jTextField1.setEnabled(true);
        this.jTextField2.setEnabled(true);
        
        }
        
    }//GEN-LAST:event_jComboBox1MouseClicked

    /**
     * @param args the command line arguments
     */
 /*   public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                JDialogTypEau dialog = new JDialogTypEau(new javax.swing.JFrame(), true,jadmin);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/

    @Action
    public void ModifierTypeEau() {
        if(jTextField1.getText().equals(""))
        {
        JOptionPane.showMessageDialog(null, "VEUILLEZ SAISIR UN TYPE D\'EAU");
              return;
        }
        if(this.jComboBox1.getSelectedItem()!=null)
        { TypeEau t =  metier.getTypeEau(this.jComboBox1.getSelectedItem().toString());
        
        //  System.out.println("t =  "+t);
        if(t==null)
            return;
        
          t.setCategorie(jTextField1.getText());
          metier.updateTypeEau(t);
          /*Modifier toutes les eaux ayant ce type d'eau*/
         List<Eau> list = metier.getAllEau();
         if(list==null)
         {   System.out.println("La liste des eaux est vide");  
             return;
         }
         for(Eau e:list)
          {
            if(e.getTypeEau().equals(this.jComboBox1.getSelectedItem().toString()))
              {  // modifiele  type
                  e.setTypeEau(jTextField1.getText());
                  metier.updateEau(e);
                 
               }
          }
             
        //ajouter sous catégorie
           if(jTextField2.getText().equals(""))
               return;
           
             EauCategorie ec = new EauCategorie();
             ec.setCategorie(jTextField2.getText());
             ec.setTypeEau(t);        
             metier.saveEauCategorie(ec);
           }
           
        else
           JOptionPane.showMessageDialog(null, "VEUILLEZ SELECTIONNER UN TYPE D\'EAU");
       // this.setVisible(false);
        fermer();
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables

    private void fermer() {
      //  throw new UnsupportedOperationException("Not yet implemented");
        this.setVisible(false);
        if(this.jadmin!=null)
           this.jadmin.setJDialogChoixmodifTypeEau(null);
        if(this.jchef!=null)
           this.jchef.setJDialogChoixmodifTypeEau(null);
    }
}
