/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDialogChoixTypeEau.java
 *
 * Created on 1 sept. 2011, 13:51:00
 */
package cpc.laboChimie.ui;

import java.util.List;
import org.jdesktop.application.Action;
import cpc.laboChimie.metier.IMetier;
import cpc.laboChimie.jpa.TypeEau;
import cpc.laboChimie.metierConfig.ParametreGestion;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;

public class JDialogChoixTypeEau extends javax.swing.JDialog {
 private List<TypeEau> list_typeEau;
 private IMetier metier;
 public JDialogAdmin jadmin;
 private JDialogFrameNormeParam JFnorm;
 private JFrameParametrefinal JFparam;
 private long idEau;
 private JFChefLabo jChef;
 private JDialogEau Jeau;
    /** Creates new form JDialogChoixTypeEau */
    public JDialogChoixTypeEau(java.awt.Frame parent, boolean modal,JFChefLabo jf ,JDialogAdmin j) {
        super(parent, modal);
        this.setTitle("SELECTIONNER UN TYPE D\'EAU");
        initComponents();
        initSpring();
            this.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.out.println("FERMETURE DE LA FENETRE");
                        fermerChoix();
                    }
                });
    
       jadmin =j ;
       if(jadmin==null){
           JOptionPane.showMessageDialog(null, "FENETRE ADMIN EST NULLE");
       }
       jChef =jf;
    }

     public IMetier getMetier() {
        return metier;
    }
     
     public long getIdEau()
     {
       return idEau;
     }
     
     public void setIdEau(long i)
     {
       idEau = i;
     }
             
     public String getNomTypeEau()
     {
       return jComboBox1.getSelectedItem().toString();
     }
     
 
public JToggleButton getBoutAjouterEau(){
    return jToggleButtonAjoutEau;
}

public void setBoutAjouterEau(JToggleButton jt){
    jToggleButtonAjoutEau = null;
}

public JToggleButton getBoutModifierEau(){
    return jToggleButtonModifierEau;
}

public void setBoutModifierEau(JToggleButton jt){
    jToggleButtonModifierEau = null;
}


  public void fermerChoix()
  {
    this.setVisible(false);
//     if(this.jadmin!=null)
//      this.jadmin.setJDialoTypeEau(null);
//     if(this.jChef!=null)
//         this.jChef.setJDialoTypeEau(null);
  }
     
    ////Initialisation du masque de saisie
    ParametreGestion parametreGestion;

    private void initSpring() {
       parametreGestion = ParametreGestion.getInstance();
       metier = parametreGestion.getMetier();
       list_typeEau =  metier.getAllTypeEau();
      if(list_typeEau==null)
          return;
      else
         System.out.println("Remlissage de la JComboBox");

   for( TypeEau t  : list_typeEau)
      { 
          if (t!=null)
      jComboBox1.addItem(t.getCategorie());
              //System.out.println(" categorie elem "+t.getCategorie());
          else
              System.out.println("Erreur pas de TypeEau");
      }
   }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jToggleButtonAjoutEau = new javax.swing.JToggleButton();
        jToggleButtonModifierEau = new javax.swing.JToggleButton();

        setName("Form"); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${defaultCloseOperation}"), this, org.jdesktop.beansbinding.BeanProperty.create("defaultCloseOperation"));
        bindingGroup.addBinding(binding);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(cpc.laboChimie.mainApp.class).getContext().getResourceMap(JDialogChoixTypeEau.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), resourceMap.getString("jPanel1.border.title"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jComboBox1.setName("jComboBox1"); // NOI18N

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), resourceMap.getString("jPanel2.border.title"))); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(cpc.laboChimie.mainApp.class).getContext().getActionMap(JDialogChoixTypeEau.class, this);
        jButton1.setAction(actionMap.get("creerNorme")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        jToggleButtonAjoutEau.setText(resourceMap.getString("jToggleButtonAjoutEau.text")); // NOI18N
        jToggleButtonAjoutEau.setName("jToggleButtonAjoutEau"); // NOI18N
        jToggleButtonAjoutEau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAjoutEauActionPerformed(evt);
            }
        });

        jToggleButtonModifierEau.setText(resourceMap.getString("jToggleButtonModifierEau.text")); // NOI18N
        jToggleButtonModifierEau.setName("jToggleButtonModifierEau"); // NOI18N
        jToggleButtonModifierEau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonModifierEauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jToggleButtonAjoutEau, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jToggleButtonModifierEau, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jToggleButtonAjoutEau)
                    .addComponent(jToggleButtonModifierEau))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jToggleButtonAjoutEauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAjoutEauActionPerformed
// TODO add your handling code here:
  if(jComboBox1.getSelectedItem()!=null)
    {// ENvoi le sur la fenêtre des normes
        String st = jComboBox1.getSelectedItem().toString();
           for(TypeEau e : list_typeEau)
          {
              if(e.getCategorie()==st)
                 setIdEau(e.getId().longValue());//id du type d'eau
          }
        if(st.equals("eaux propres")){
            
        Jeau = new JDialogEau(null,true,null,jadmin);
        Jeau.setTitle("AJOUT D\'UNE EAU PROPRE");
        Jeau.getJlabelIdClientEau().setVisible(false);
        Jeau.getjtexFieldidClient().setVisible(false);
        Jeau.getJlabelidEau().setVisible(false);
        Jeau.getIdEau().setVisible(false);
        System.out.println(" Bienvennue dans la fenetre eaux propres");
          Jeau.getjToggleButtonEnregistrer().setEnabled(true);
         //desactiv le bouton de modification

           Jeau.getjToggleButtonModifier().setEnabled(false);
           Jeau.setVisible(true);

         }
        if(st.equals("eaux usées")){
        JDialogEauUsee Jeau2 = new JDialogEauUsee(null,true,jadmin);
        Jeau2.setTitle("AJOUT D\'UNE EAU USEE");
        Jeau2.getJlabelIdClientEau().setVisible(false);
        Jeau2.getjtexFieldidClient().setVisible(false);
        Jeau2.getJlabelidEau().setVisible(false);
        Jeau2.getIdEau().setVisible(false);
        System.out.println(" Bienvennue dans la fenetre eaux usees");
          Jeau2.getjToggleButtonEnregistrer().setEnabled(true);
         //desactiv le bouton de modification

           Jeau2.getjToggleButtonModifier().setEnabled(false);
           Jeau2.setVisible(true);

         }

        if(st.equals("eaux bétons")){
        JDialogEauBeton Jeau3 = new JDialogEauBeton(null,true,jadmin);
        Jeau3.setTitle("AJOUT D\'UNE EAU DE BETON");
        Jeau3.getJlabelIdClientEau().setVisible(false);
        Jeau3.getjtexFieldidClient().setVisible(false);
        Jeau3.getJlabelidEau().setVisible(false);
        Jeau3.getIdEau().setVisible(false);
        System.out.println(" Bienvennue dans la fenetre eaux usees");
          Jeau3.getjToggleButtonEnregistrer().setEnabled(true);
         //desactiv le bouton de modification

           Jeau3.getjToggleButtonModifier().setEnabled(false);
           Jeau3.setVisible(true);

         }
        
        
    }    
    
}//GEN-LAST:event_jToggleButtonAjoutEauActionPerformed

private void jToggleButtonModifierEauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonModifierEauActionPerformed
// TODO add your handling code here:
  if(jComboBox1.getSelectedItem()!=null)
    {// ENvoi le sur la fenêtre des normes
        String st = jComboBox1.getSelectedItem().toString();
           for(TypeEau e : list_typeEau)
          {
              if(e.getCategorie()==st)
                 setIdEau(e.getId().longValue());//id du type d'eau
          }
    }    
   
}//GEN-LAST:event_jToggleButtonModifierEauActionPerformed

    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                JDialogChoixTypeEau dialog = new JDialogChoixTypeEau(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/

    @Action
    public void creerNorme() {
  if(jComboBox1.getSelectedItem()!=null)
    {// ENvoi le sur la fenêtre des normes
        String st = jComboBox1.getSelectedItem().toString();
           for(TypeEau e : list_typeEau)
          {
              if(e.getCategorie()==st)
                 setIdEau(e.getId().longValue());//id du type d'eau
          }
            
        JFnorm = new JDialogFrameNormeParam(null,true,this);
        if(this.jadmin!=null)
        {  if(this.jadmin.getOpNorme()==0){//Modification de la norme code opération 0
           JFnorm.setCodeOperation(0);
           JFnorm.getjToggleButtonEnregistrer().setEnabled(false);
           JFnorm.getjToggleButtonModifier().setEnabled(true);
           JFnorm.setVisible(true);
        }
        if(this.jadmin.getOpNorme()==1)
        {//Lister les normes
        JFnorm.getjToggleButtonEnregistrer().setEnabled(false);
        JFnorm.getjToggleButtonModifier().setEnabled(true);
        JFnorm.setVisible(true);
                   
        }
       if(this.jadmin.getOpNorme()==-1)
        {//Ajouter une Norme Code operation 4
            JFparam = new JFrameParametrefinal(null, true, null, this,null,null,null);
           // JFparam.getjToggleButtonEnregistrer().setEnabled(true);
            JFparam.getjToggleButtonModifier().setEnabled(false);
            JFparam.setCodeOperation(1);
            //   JFparam.getJLabelAjouter().setVisible(false);
           // JFparam.getJLabelModifier().setVisible(false);*/
            JFparam.getJLabelListerNorme().setVisible(false);
            JFparam.getjToggleButtonListerNormes().setVisible(false);
        
            JFparam.setItypdEau(this.getIdEau());
            JFparam.setVisible(true);

        }
       
        if(this.jadmin.getOpNorme()==10) //Consulter la liste des normes du type d'eau
        {  
          //  JFnorm.getj
           //JFnorm.setCodeOperation(10);
           JFnorm.setVisible(true);
        }
      }
        if(this.jChef!=null)
        {  if(this.jChef.getOpNorme()==0){//Modification de la norme code opération 0
           JFnorm.setCodeOperation(0);
           JFnorm.getjToggleButtonEnregistrer().setEnabled(false);
           JFnorm.getjToggleButtonModifier().setEnabled(true);
           JFnorm.setVisible(true);
        }
        if(this.jChef.getOpNorme()==1)
        {//Lister les normes
        JFnorm.getjToggleButtonEnregistrer().setEnabled(false);
        JFnorm.getjToggleButtonModifier().setEnabled(true);
        JFnorm.setVisible(true);
                   
        }
       if(this.jChef.getOpNorme()==-1)
        {//Ajouter une Norme Code operation 4
            JFparam = new JFrameParametrefinal(null, true, null, this,null,null,null);
           // JFparam.getjToggleButtonEnregistrer().setEnabled(true);
            JFparam.getjToggleButtonModifier().setEnabled(false);
            JFparam.setCodeOperation(1);
            //   JFparam.getJLabelAjouter().setVisible(false);
           // JFparam.getJLabelModifier().setVisible(false);*/
            JFparam.getJLabelListerNorme().setVisible(false);
            JFparam.getjToggleButtonListerNormes().setVisible(false);
        
            JFparam.setItypdEau(this.getIdEau());
            JFparam.setVisible(true);

        }
       
        if(this.jChef.getOpNorme()==10) //Consulter la liste des normes du type d'eau
        {  
          //  JFnorm.getj
           //JFnorm.setCodeOperation(10);
           JFnorm.setVisible(true);
        }
           
        }
        
    }
      fermerChoix();
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jToggleButtonAjoutEau;
    private javax.swing.JToggleButton jToggleButtonModifierEau;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
